### PR TITLE
Remove deprecated javax.xml.bind.DatatypeConverter dep for Java9 comp…

### PR DESCRIPTION
**Pull request by thosmos**
based on the same fix used in Clojurescript here:
https://github.com/clojure/clojurescript/commit/544c1b77d76d48f234cdb03746ea993158c46aff

### CODE REVIEW

**Comment by ohpauleez** [comment]
Thanks for pulling this together!  I think we should just collapse the `bytes-to-base64-str` into the short hash function.

**Comment by ohpauleez** [comment]
Thanks for making the changes!  No worries about squashing, but I appreciate you asking.
Have you signed a Cognitect Contributor's Agreement before?

**Comment by thosmos** [comment]
I've filled out the Rich Hickey CA as linked from https://clojure.org/community/contributing, but using my old github username "thos37".   I thought I sent another CA a while back with my current username "thosmos", but it's still the old one on the list.  You can see my username change message here: https://github.com/thos37   It looks like the CA form is broken at the moment (name field is not editable)

**Comment by neuromantik33** [comment]
Any chance this can get merged one day? This is quite a show stopper for running any vase application with Java11

**Comment by ddeaguiar** [comment]
I found no CA. I made the change in the context of other changes so closing this PR.

**Comment by thosmos** [comment]
> I found no CA. I made the change in the context of other changes so closing this PR.

My CA is under my username "thosmos" at https://clojure.org/community/contributors

**Comment by ddeaguiar** [comment]
Ok, sorry about that. I was apparently looking in the wrong place.

**Comment by thosmos** [comment]
> Ok, sorry about that. I was apparently looking in the wrong place.

No problem!  I'm glad the fix got committed!

**Pull request closed without merging**
